### PR TITLE
added endpoint_overrided to get_container method in proxy

### LINKED ISSUE #170: obs get_container method endpoint_override missing
The get_container() method needs endpoint_override in order to get it work...similarly as other methods of _proxy.py

### PR DESCRIPTION
**Pull request by kucerakk**

### CODE REVIEW

**Review by gtema — COMMENTED** [review]
I think `requests_auth=self._get_req_auth(endpoint)`is missing

**Comment by kucerakk** [comment]
> I think `requests_auth=self._get_req_auth(endpoint)`is missing

added

**Review by tischrei — APPROVED** [review]

**Comment by gtema** [comment]
regate

**Comment by gtema** [comment]
regate

**Comment by gtema** [comment]
regate

**Comment by gtema** [comment]
regate

**Comment by gtema** [comment]
regate

**Pull request merged**
