### PR TITLE
Set ignore_missing=True for DWS find and delete methods

### PR DESCRIPTION
**Pull request by vineet-pruthi**
- Set ignore_missing=True for DWS find and delete methods.
- Standardized PEP8 formatting for DWS using ruff and black formatters.

### CODE REVIEW

**Comment by vineet-pruthi** [comment]
recheck

**Review by anton-sidelnikov — DISMISSED** [review]

**Comment by anton-sidelnikov** [comment]
recheck

**Comment by Persimmonboy** [comment]
recheck

**Comment by vineet-pruthi** [comment]
recheck

**Comment by vineet-pruthi** [comment]
recheck

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by anton-sidelnikov — APPROVED** [review]

**Comment by anton-sidelnikov** [comment]
regate

**Pull request merged**
