### PR TITLE
[CLI] Initialize cloud layer in CCE and RDS

### LINKED ISSUE #151: [CCE] cluster deletion not working
## Versions
```
$ openstack --version
openstack 5.4.0
```
```
$ sudo pip show otcextensions
Name: otcextensions
Version: 0.13.0
```

## Command used
`openstack --os-cloud machine cce cluster delete addontest-tpoa -v`
or
`openstack --os-cloud machine cce cluster delete 3eacd30f-8bbc-11eb-8691-0255ac1017b0 -v`

## Command output
```
START with options: --os-cloud machine cce cluster delete addontest-tpoa -v
/usr/lib/python3.9/site-packages/barbicanclient/__init__.py:57: UserWarning: The secrets module is moved to barbicanclient/v1 directory, direct import of barbicanclient.secrets will be deprecated. Please import barbicanclient.v1.secrets instead.
  warnings.warn("The %s module is moved to barbicanclient/v1 "
/usr/lib/python3.9/site-packages/yaql/language/utils.py:54: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  SequenceType = collections.Sequence
command: cce cluster delete -> otcextensions.osclient.cce.v2.cluster.DeleteCCECluster (auth=True)
Using auth plugin: password
'Connection' object has no attribute 'delete_cce_cluster'
END return value: 1
```

### LINKED ISSUE #160: [RDS] instance can't be removed via CLI
#### Versions
```
openstacksdk==0.55.0
python-openstackclient==5.5.0
```

`otcextensions` - up to date `master` (a258cc00a536dad1bfab5f86103bf1b7a450ae4c)

#### Executed test
```
/home/akachuri/PycharmProjects/python-otcextensions/.tox/venv/bin/python -m openstackclient.shell --os-cloud machine rds instance delete tf_rds_instance_j3b
'Namespace' object has no attribute 'name'
```

Same reproduces for `0.13.0`

### PR DESCRIPTION
**Pull request by outcatcher**
### Description

Add SDK loading to `sdk_connection` in `DeleteCCECluster.take_action`

Resolve #151 
Resolve #160

### CODE REVIEW

**Comment by tischrei** [comment]
Your stuff is fine.
Please merge master into your branch after the following PR is through the gate process:
https://github.com/opentelekomcloud/python-otcextensions/pull/157

...to ensure that py3* tests are fine.

**Comment by gtema** [comment]
Nope, it's not fine. 
generally - we do not want to register OTCE in every command class, but rely on profile: otc being present in config or the client class to do that in the initialization (https://github.com/opentelekomcloud/python-otcextensions/blob/master/otcextensions/osclient/cce/client.py#L42)

**Comment by tischrei** [comment]
I double checked the functionality of the CLI right now and it is working fine from my perspective. I deleted my first comment.

**Comment by outcatcher** [comment]
@gtema 
> Nope, it's not fine.
> generally - we do not want to register OTCE in every command class, but rely on profile: otc being present in config or the client class to do that in the initialization (https://github.com/opentelekomcloud/python-otcextensions/blob/master/otcextensions/osclient/cce/client.py#L42)

But why is it not loaded then? There is `conn.cce` object, but there are no `CceMixin` methods in the connection itself. 
I've done this based on what was done in [`compute.v2.server.SetServer`](https://github.com/opentelekomcloud/python-otcextensions/blob/master/otcextensions/osclient/compute/v2/server.py#L124). What is the correct way to use `conn.delete_cce_cluster` in this case, if there is any?

**Comment by gtema** [comment]
server.SetServer is a different case, since we only override a single command without overriding the client itself.

Are you perhaps trying a totally unforeseen calling pattern? Presence of conn.cce is possible only when OTCE is already registered. MixIns are injected in https://github.com/opentelekomcloud/python-otcextensions/blob/master/otcextensions/sdk/__init__.py#L345 next to the registration of services. So I assume you might be somehow bypassing correct initialization. Are you able to use conn.cce (i.e. conn.cce.clusters())?

**Comment by outcatcher** [comment]
To be discussed next week

**Review by gtema — CHANGES_REQUESTED** [review]
please also add same into cluster creation, rds creation and deletion, since they also rely on cloud layer

**Review by gtema — DISMISSED** [review]

**Comment by outcatcher** [comment]
recheck-post

**Comment by gtema** [comment]
regate

**Review by gtema — APPROVED** [review]

**Pull request merged**
